
export const GET_ARTISTS = "GET_ARTISTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const ORDER_BY_LESS_EXPENSIVE = "ORDER_BY_LESS_EXPENSIVE"
export const ORDER_BY_MORE_EXPENSIVE = "ORDER_BY_MORE_EXPENSIVE"
export const CLEAN_PRODUCT_ID = 'CLEAN_PRODUCT_ID'
export const SHOW_ALL_PRODUCTS = "SHOW_ALL_PRODUCTS"
export const FILTER_BY_ARTIST = "FILTER_BY_ARTIST"
