
export const GET_ARTISTS = "GET_ARTISTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"
export const CLEAN_PRODUCT_ID = 'CLEAN_PRODUCT_ID'
export const SHOW_ALL_PRODUCTS = "SHOW_ALL_PRODUCTS"
export const FILTER_BY_ARTIST = "FILTER_BY_ARTIST"
export const ADD_FILTER_ARTIST = "UPDATE_FILTER_ARTIST"
export const DELETE_FILTER = "DELETE_ARTIST_FROM_FILTER"
export const ADD_PRICE_TYPE = "ADD_PRICE_TYPE"
export const FILTER_BY_MEDIUM = "FILTER_BY_MEDIUM"
export const ADD_FILTER_MEDIUM = "ADD_FILTER_MEDIUM"
export const NOT_FOUND = "NOT_FOUND"
export const ADD_PRODUCT_TO_CARRITO = "ADD_PRODUCT_TO_CARRITO"
export const DELETE_PRODUCT_FROM_CARRITO = "DELETE_PRODUCT_FROM_CARRITO"
export const CHANGE_COUNT_PRODUCT_FROM_CARRITO = "CHANGE_COUNT_PRODUCT_FROM_CARRITO"

export const DELETE_ARTWORKS = "DELETE_ARTWORKS"


export const ADD_FILTERS = "ADD_FILTERS"