export const GET_ARTISTS = "GET_ARTISTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"
export const CLEAN_PRODUCT_ID = 'CLEAN_PRODUCT_ID'
export const SHOW_ALL_PRODUCTS = "SHOW_ALL_PRODUCTS"
export const FILTER_BY_ARTIST = "FILTER_BY_ARTIST"
export const ADD_FILTER_ARTIST = "UPDATE_FILTER_ARTIST"
export const DELETE_FILTER = "DELETE_ARTIST_FROM_FILTER"
export const ADD_PRICE_TYPE = "ADD_PRICE_TYPE"
export const FILTER_BY_MEDIUM = "FILTER_BY_MEDIUM"
export const ADD_FILTER_MEDIUM = "ADD_FILTER_MEDIUM"
export const NOT_FOUND = "NOT_FOUND"
export const ADD_PRODUCT_TO_CARRITO = "ADD_PRODUCT_TO_CARRITO"
export const DELETE_PRODUCT_FROM_CARRITO = "DELETE_PRODUCT_FROM_CARRITO"
export const DELETE_PRODUCT_FROM_CARRITO_BOARD = "DELETE_PRODUCT_FROM_CARRITO_BOARD"
export const GET_PRODUCTS_FROM_CARRITODB = "GET_PRODUCTS_FROM_CARRITODB"
export const CHANGE_COUNT_PRODUCT_FROM_CARRITO = "CHANGE_COUNT_PRODUCT_FROM_CARRITO"
export const DELETE_ARTWORKS = "DELETE_ARTWORKS"
export const ADD_FILTERS = "ADD_FILTERS"
export const GET_USER = "GET USER"
export const LOG_LOCAL = "LOG_LOCAL"
export const VACIAR_USER = "VACIAR_USER"
export const SET_USER = "SET_USER"
export const UPDATE_USER = "UPDATE_USER"
export const FIND_USER_BY_ID = "FIND_USER_BY_ID"
export const SEND_EMAIL = "SEND_EMAIL"
export const GET_USERS = 'GET_USERS'

export const ADD_PRODUCTO_TO_FAVOURITES = 'ADD_PRODUCTO_TO_FAVOURITES'
export const DELETE_PRODUCTO_FROM_FAVOURITES = 'DELETE_PRODUCTO_FROM_FAVOURITES'
export const GET_FAVOURITES = 'GET_FAVOURITES'
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const GET_HISTORY = "GET_HISTORY"

export const GET_ALL_ORDERS = "GET_ALL_ORDERS"

export const GET_ORDERS_USER = "GET_ORDERS_USER"
export const GET_ONE_ORDER = "GET_ONE_ORDER"
export const FILTER_ORDER_APROVED = "FILTER_ORDER_APROVED"
export const FILTER_ORDER_REJECTED = "FILTER_ORDER_REJECTED"

export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL"

export const FILTER_ORDER_APROVED_USER = "FILTER_ORDER_APROVED_USER"
export const FILTER_ORDER_REJECTED_USER = "FILTER_ORDER_REJECTED_USER"
export const GET_ONE_ORDER_USER = "GET_ONE_ORDER_USER"
